remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
title: A 3D-printable tiling of aperiodic monotiles
description: A project of the Rectangle Bounded by Cemeteries at Diagonally Opposite Vertices Nerds Association
